version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_auth_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ifortex
      POSTGRES_PASSWORD: ifortex
      POSTGRES_DB: auth_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.utf8"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local