spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db
    username: ifortex
    password: ifortex

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      ifortex:
        internship:
          auth_service: DEBUG